### ISSUE TITLE
Trying to Use with Ignite Model

### ISSUE THREAD

**Issue by JeffCdev** [cmaion/polar#10]
Hi Cmaion, is there any type of logging or way to turn on debugging? I was very excited to find your app (when I purchased my Polar Ignite, I didn't realize that there was no "local only" option of data storage/tracking) but I am unable to connect to my Ignite, with this error:
r/lib/polar_usb.rb:29:in `initialize': Could not find Polar USB device (PolarUsb::PolarUsbDeviceError) I've tried both the libusb-1.0.dll from libusb.info and the one from your app.  I am running ruby 2.5.5p157 (2019-03-15 revision 67260) [i386-mingw32]. If you think that makes a different, I'll try the 2.3.3 version

**Comment by cmaion** [comment]
Hi Jeff

Can you search for the USB vendor ID and product ID of your Ignite watch?
For Windows, this should be somewhere in the hardware tab of the device properties for your watch (VID_xxxx and PID_xxxx).

Cheers,
Cedric

**Comment by JeffCdev** [comment]
Hi Cedric, Wow!!!  Thanks for getting back to me so quickly.  Here's the info about the Polar Ignite from USBDeview:
Device Name 	Description 	Device Type 	Connected 	Safe To Unplug 	Disabled 	USB Hub 	Drive Letter 	Serial Number 	Created Date 	Last Plug/Unplug Date 	VendorID 	ProductID 	Firmware Revision 	USB Class 	USB SubClass 	USB Protocol 	Hub / Port 	Computer Name 	Vendor Name 	Product Name 	ParentId Prefix 	Service Name 	Service Description 	Driver Filename 	Device Class 	Device Mfg 	Friendly Name 	Power 	USB Version 	Driver Description 	Driver Version 	Driver InfSection 	Driver InfPath 	Instance ID 	Capabilities
Polar Ignite	Polar CDC Config	Communication	Yes	Yes	No	No	COM5	XXXXXXX	7/31/2019 10:49:52 AM	7/31/2019 5:05:52 PM	0da4	0014	1.00	02	02	01	 	PC	 	 	 	usbser	Polar CDC Config	usbser.sys	Ports	Polar Electro Oy	Polar CDC Config (COM5)	500 mA	2.00	Polar CDC Config	6.0.2600.5	DriverInstall	oem160.inf	USB\VID_0DA4&PID_0014\5CBCAC28	Removable, UniqueID, SurpriseRemovalOK

**Comment by cmaion** [comment]
No idea if the USB protocol on the Ignite is the same as previous models, but you may want to try to change the following line in polar/lib/polar_usb.rb (line 25) from

      @usb_product = 0x0008

to

      @usb_product = 0x0014

Let me know if it works!

**Comment by JeffCdev** [comment]
Hi Cedric,
unfortunately, no joy with changing the product.  I've been trying a couple of other approaches (https://github.com/rsc-dev/loophole) without any luck either.  :(

**Comment by cmaion** [comment]
Hi

I would have expected a different message than "Could not find Polar USB device" with that USB product ID. But as I don't have an Ignite at hand that was just a shot in the dark.
Not sure I can help until somebody else with an Ignite can check it's USB interface.

**Comment by cmaion** [comment]
Hi,

Thinking about it: did you already have the windows polar app running/connected to the watch?
If it was the case you may want to stop (or even uninstall) the polar app and see if you can connect.
2 apps can't use the same USB device at the same time, I guess.

**Comment by rapmaste** [comment]
Hello.
I tested with my brand new Ignite, and it didn't work all the way. First, I changed the usb_product to 0x0014, and then it actually recognizes the Ignite watch. The polar_ftp program also gets the serial number correctly, but cannot get a file listing.
The result apparently is an I/O error. The traceback looks like this:

Connected to Polar Ignite serial 69FF452E
Listing content of '/'
Traceback (most recent call last):
        8: from ./polar_ftp:23:in `<main>'
        7: from /home/Downloads/polar/lib/polar_ftp.rb:23:in `dir'
        6: from /home/Downloads/polar/lib/polar_usb.rb:55:in `request'
        5: from /home/Downloads/polar/lib/polar_usb.rb:145:in `usb_write'
        4: from /usr/lib64/ruby/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:465:in `interrupt_transfer'
        3: from /usr/lib64/ruby/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/dev_handle.rb:544:in `submit_transfer'
        2: from /usr/lib64/ruby/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/transfer.rb:246:in `submit_and_wait'
        1: from /usr/lib64/ruby/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/transfer.rb:217:in `submit!'
/usr/lib64/ruby/gems/2.5.0/gems/libusb-0.6.4-x86_64-linux/lib/libusb/constants.rb:68:in `raise_error': LIBUSB::ERROR_

**Comment by cmaion** [comment]
Hi

I guess that it's the same situation as the Vantage (https://github.com/cmaion/polar/issues/12#issuecomment-537390508)
I don't own one of those, so can't test & see if just porting the USB interface from HID to CDC ADM would be enough.

**Comment by ilavidas** [comment]
Hello,
I'm facing the same issue with Vantage M. I guess Polar decided to change the USB interface for all of their new watches.

Following from [here](https://github.com/cmaion/polar/issues/12#issuecomment-537390508), this is what I get from dmesg
`usb 2-2.1: new full-speed USB device number 25 using xhci_hcd
usb 2-2.1: New USB device found, idVendor=0da4, idProduct=0014, bcdDevice= 1.00
usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 2-2.1: Product: Polar Vantage M
usb 2-2.1: Manufacturer: Polar Electro Oy
usb 2-2.1: SerialNumber: foo__bar
cdc_acm 2-2.1:1.0: ttyACM0: USB ACM device`

Unfortunately I'm unfamiliar with Ruby and USB interfaces and therefore I've got no clue on how to start working on a polar_acm.rb file.
I'll be happy to contribute towards a new Polar watch for you, if more people are willing to follow suit.

**Comment by JeffCdev** [comment]
One more for a contribution as well.

**Comment by cmaion** [comment]
Thanks guys. Might not be necessary after all, progress is being done (blindly on my side, but still promising).

See https://github.com/cmaion/polar/issues/12 if you want to help!

**Comment by cmaion** [comment]
Closing this, should now work with Polar Ignite & Vantage watches.

**Comment by JeffCdev** [comment]
Hey cmaion, just checked to see what was happening with your application, and it was like Christmas morning today!!!!  I was able to set it up on a Rpi, and do my first sync.  I can not thank you enough for your efforts, I really didn't want to enter into the Faustian bargain of privacy vs. data, and you've made that possible.  Do you have a "Buy Me a Beer / Coffee" set up so that I can send you a more tangible expression of my appreciation?

**Comment by cmaion** [comment]
Hi @JeffCdev, glad it works for you too!
Always happy to try local beers (microbreweries seem to be blooming in my part of the world), but you don't need to send anything, your kind words are more than enough!

Cheers
