### ISSUE TITLE
functionality of extracting the RR record from the exercise (Polar V800)

### ISSUE THREAD

**Issue by kowalczuk** [cmaion/polar#14]
is there a chance to add the functionality of extracting the RR record from the exercise.
I'm sure polar collects such data: some time ago I downloaded all polar account data (includes training sessions, settings, product information, routes, calendar entries and more) and there were json files of exercises containing RR records.
Is it possible to add extracting such data in your script?
(RR is very valuable data for training load analysis)

**Comment by kowalczuk** [comment]
this is part of json from exercise (with RR data)
  "exercises": [
    {
      "startTime": "2017-09-12T16:05:50.000",
      "stopTime": "2017-09-12T17:14:45.875",
      "timezoneOffset": 120,
      "duration": "PT4135.875S",
      "distance": 6105.39990234375,
      "sport": "HIKING",
      "latitude": 52.239365,
      "longitude": 20.97761,
      "descent": 14.935400009155273,
      "kiloCalories": 495,
      "heartRate": {..},
      "speed": {..},
      "zones": {
        "heart_rate": [..],
        "speed": [..]
      },
      "autoLaps": [..],
      "samples": {
        "rr": [
          {
            "duration": "PT0.521S",
            "offline": false
          },
          {
            "duration": "PT0.525S",
            "offline": false
          },
          {
            "duration": "PT0.531S",
            "offline": false

**Comment by cmaion** [comment]
Hi,

Yes, the RR intervals are in there.
For some reason, the protobuf library that I use to read the files has a bug and fails to extract them.
I would probably need to switch to another protobuf library (and a faster one...).

**Comment by kowalczuk** [comment]
Hi, thanks for the answer.
I took your *.proto files and compiled them for Python using protoc ver 3.9.0
In proto files I added only a few imports and 'syntax = "proto2";'
Then I used one SAMPLES file and I received RR intervals

If it helps then I can share my repository.
But privately (because I don't know Python and I don't know Protocol Buffers)

**Comment by cmaion** [comment]
Yes I also checked other tools that can properly parse the samples file.
I'll check how easy it is (or not) to switch to the official protobuf ruby gem.

**Comment by cmaion** [comment]
Done, that was actually quite smooth. And this is so much faster.
Run ```gem install google-protobuf``` and check ```polar_training2rrtxt```

**Comment by kowalczuk** [comment]
I have one more question but I would not like to fool around in the forum.
Can I ask you privately?
