### ISSUE TITLE
Polar RC3 Process Error

### ISSUE THREAD

**Issue by jjdheremans** [cmaion/polar#15]
Hello,

Thank you first for the development of this interesting tool. I didn't transfer my running data for a while because of the absence of any convenient tool on linux...

I'm using an old device RC3 GPS, which seems to be well detected by `polar_usb` (device name as well as serial number are displayed). However, the execution fails when reading data. Here is the output of `sudo ./polar_ftp DIR /`:

`
Connected to Polar RC3 GPS serial ***************
Listing content of '/'
Traceback (most recent call last) `

	6: from ./polar_ftp:23:in '<main>'
	5: from /home/julien/Téléchargements/polar-master/lib/polar_ftp.rb:23:in 'dir'
	4: from /home/julien/Téléchargements/polar-master/lib/polar_usb.rb:57:in 'request'
	3: from /home/julien/Téléchargements/polar-master/lib/polar_usb.rb:65:in 'read'
	2: from /home/julien/Téléchargements/polar-master/lib/polar_usb.rb:65:in 'loop'
	1: from /home/julien/Téléchargements/polar-master/lib/polar_usb.rb:88:in 'block in read'
`/home/julien/Téléchargements/polar-master/lib/polar_usb.rb:208:in 'process_error': Error: 16? (PolarUsb::PolarUsbError)`

 I suppose that the data formatting are not the same as with V800. What could I do to fix it ?

Thx for your help !

**Comment by cmaion** [comment]
Hi,

Not sure if the RC3 data files have the same format as the V800 (protobuf).

Have you tried https://github.com/pcolby/bipolar on a Windows system? It hooks into PolarFlow and extract the datafiles. If it works, this would tell if those files have same format or not.

**Comment by jjdheremans** [comment]
Hi @cmaion, thank you for your response.
I will give it a try and let you know. In fact I doubt since RC3 isn't compatible with FlowSync but requires the older polar software "WebSync" to extract data. 

Anyway, how did you proceed to determine the data formatting? I would be tempted to try to develop a new feature, but I have no idea of how to start... Have you a link to some further information or any other clue ? All I can read starting from your rubi script is a series of integer data...

**Comment by cmaion** [comment]
Hi,

Sorry, completely forgot to answer!

In the case of the V800-generation watches, all files are encoded using Google protobuf (for which you need the specs to interpret, but I have no merit, others already did the work here).

You also need to find out the USB protocol layer works. Wireshark can be useful to dump actual packets exchanged between the watch and the official Polar software. You "just" have to try to make sense of those (packet structure: headers/length/payload...).

Good luck!
