### ISSUE TITLE
Stops downloading from Watch

### ISSUE THREAD

**Issue by tdpo2** [cmaion/polar#17]
C:\polar-master>C:\Ruby24\bin\ruby.exe C:\polar-master\polar_ftp -d//./COM3 SYNC C:\polararchive\
Connected to ? serial ?
Synchronizing to 'C:\polararchive\'
Listing content of '/'
Downloading '/PRODCONF.TXT' as 'C:\polararchive\/PRODCONF.TXT'
Listing content of '/SS/'
Listing content of '/SDLOGS/'
Listing content of '/SDSIMU/'
Listing content of '/SYS/'
Listing content of '/SYS/BT/'
Listing content of '/SYS/GPS/'
Downloading '/SYS/GPS/ALMAINFO.BPB' as 'C:\polararchive\/SYS/GPS/ALMAINFO.BPB'
Listing content of '/SYS/SPORT/'
Listing content of '/SYS/SPORT/1/'
Downloading '/SYS/SPORT/1/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/1/SPORT.BPB'
Listing content of '/SYS/SPORT/17/'
Downloading '/SYS/SPORT/17/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/17/SPORT.BPB'
Listing content of '/SYS/SPORT/2/'
Downloading '/SYS/SPORT/2/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/2/SPORT.BPB'
Listing content of '/SYS/SPORT/18/'
Downloading '/SYS/SPORT/18/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/18/SPORT.BPB'
Listing content of '/SYS/SPORT/5/'
Downloading '/SYS/SPORT/5/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/5/SPORT.BPB'
Listing content of '/SYS/SPORT/23/'
Downloading '/SYS/SPORT/23/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/23/SPORT.BPB'
Listing content of '/SYS/SPORT/15/'
Downloading '/SYS/SPORT/15/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/15/SPORT.BPB'
Listing content of '/SYS/SPORT/34/'
Downloading '/SYS/SPORT/34/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/34/SPORT.BPB'
Listing content of '/SYS/SPORT/3/'
Downloading '/SYS/SPORT/3/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/3/SPORT.BPB'
Listing content of '/SYS/SPORT/11/'
Downloading '/SYS/SPORT/11/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/11/SPORT.BPB'
Listing content of '/SYS/SPORT/83/'
Downloading '/SYS/SPORT/83/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/83/SPORT.BPB'
Listing content of '/SYS/SPORT/16/'
Downloading '/SYS/SPORT/16/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/16/SPORT.BPB'
Listing content of '/SYS/SPORT/72/'
Downloading '/SYS/SPORT/72/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/72/SPORT.BPB'
Listing content of '/SYS/SPORT/74/'
Downloading '/SYS/SPORT/74/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/74/SPORT.BPB'
Listing content of '/SYS/SPORT/73/'
Downloading '/SYS/SPORT/73/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/73/SPORT.BPB'
Listing content of '/SYS/SPORT/68/'
Downloading '/SYS/SPORT/68/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/68/SPORT.BPB'
Listing content of '/SYS/SPORT/82/'
Downloading '/SYS/SPORT/82/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/82/SPORT.BPB'
Listing content of '/SYS/SPORT/69/'
Downloading '/SYS/SPORT/69/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/69/SPORT.BPB'
Listing content of '/SYS/SPORT/75/'
Downloading '/SYS/SPORT/75/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/75/SPORT.BPB'
Listing content of '/SYS/SPORT/76/'
Downloading '/SYS/SPORT/76/SPORT.BPB' as 'C:\polararchive\/SYS/SPORT/76/SPORT.BPB'
Listing content of '/SYS/FIXSPORT/'
Listing content of '/SYS/FIXSPORT/15/'
Downloading '/SYS/FIXSPORT/15/SPORT.BPB' as 'C:\polararchive\/SYS/FIXSPORT/15/SPORT.BPB'
Listing content of '/SYS/FIXSPORT/111/'
Downloading '/SYS/FIXSPORT/111/SPORT.BPB' as 'C:\polararchive\/SYS/FIXSPORT/111/SPORT.BPB'
Listing content of '/SYS/FIXSPORT/126/'
Downloading '/SYS/FIXSPORT/126/SPORT.BPB' as 'C:\polararchive\/SYS/FIXSPORT/126/SPORT.BPB'
Listing content of '/SYS/FIXSPORT/127/'
Downloading '/SYS/FIXSPORT/127/SPORT.BPB' as 'C:\polararchive\/SYS/FIXSPORT/127/SPORT.BPB'
Listing content of '/SYS/FONT/'
Listing content of '/SYS/LANG/'
Listing content of '/SYS/KEYS/'
Downloading '/SYS/KEYS/PUBLIC' as 'C:\polararchive\/SYS/KEYS/PUBLIC'
Listing content of '/SYS/SIGN/'
Listing content of '/SYS/MEMORY/'
Downloading '/SYS/DEVSET.BPB' as 'C:\polararchive\/SYS/DEVSET.BPB'
Downloading '/SYS/DBGSTATS.BPB' as 'C:\polararchive\/SYS/DBGSTATS.BPB'
Listing content of '/U/'
Listing content of '/U/0/'
Listing content of '/U/0/AUTOS/'
Downloading '/U/0/AUTOS/AUTOS000.BPB' as 'C:\polararchive\/U/0/AUTOS/AUTOS000.BPB'
Downloading '/U/0/AUTOS/AUTOS001.BPB' as 'C:\polararchive\/U/0/AUTOS/AUTOS001.BPB'

Sometimes even hangs at "Listing content of '/'"

Couple of times download hanged but I still got info about better charge %.

**Comment by cmaion** [comment]
Hi

What watch is this? any error message?

**Comment by tdpo2** [comment]
Vantage M. No errors.

**Comment by tdpo2** [comment]
> Hi
> 
> What watch is this? any error message?

Any idea why this is happening?

**Comment by cmaion** [comment]
Not really, might be something specific to Windows, I would guess that it's waiting for available data on the serial port.

If you have some coding skill, you may want to add debug code in https://github.com/cmaion/polar/blob/eca28cd92fcd9d4b6ee00b8994bfff323b0df388/lib/polar_usb_acm.rb#L54

(ie, dump all packets received so that we get a better idea of what might go wrong)

**Comment by cmaion** [comment]
You may also want to change the delay here: 
https://github.com/cmaion/polar/blob/eca28cd92fcd9d4b6ee00b8994bfff323b0df388/lib/polar_usb_acm.rb#L72

replace 0.001 with 0.01 and see if solves anything

**Comment by tdpo2** [comment]
I don't. Can you write it?

V V sre., 1. jul. 2020 ob 17:15 je oseba cmaion <notifications@github.com>
napisala:

**Comment by tdpo2** [comment]
maybe this will help:

C:\polar-master>C:\Ruby24\bin\ruby.exe C:\polar-master\polar_ftp -d//./COM3 SYNC C:\polararchive\
Connected to ? serial ?
Synchronizing to 'C:\polararchive\'
Listing content of '/'
C:/polar-master/lib/polar_usb_acm.rb:117:in `read': Received unexpected data after completion of previous transfer (PolarUsb::PolarUsbProtocolError)
PACKET: a 10 a b 4a 4f 55 52 4e 41 4c 2e 44 41 54 10 80 50 a 10 a c 50 52 4f 44 43 4f 4e 46 2e 54 58 54 10 1b a 7 a 3 53 53 2f 10 0 a b a 7 53 44 4c 4f 47 53 2
 10 0 a b a 7 53 44 53 49 4d 55 2f 10 0 a 8 a 4 53 59 53 2f 10 0 a 6 a 2 55 2f 10 0 a e a a 53 59 53 4c 4f 47 2e 42 50 42 10 19 a f a b 53 59 53 43 4f 4e 46 2e
42 50 42 10 6 a d a 9 4d 55 53 43 46 2e 42 49 4e 10 c a e a a 53 44 53 49 4d 55 2e 42 50 42 10 e a 11 a c 50 52 4f 44 44 41 54 41 2e 42 49 4e 10 98 1 a e a a 5
 44 4c 4f 47 53 2e 42 50 42 10 20 a 11 a b 44 42 47 54 52 43 31 2e 42 49 4e 10 f4 e0 2 a f a a 53 59 53 4c 4f 47 2e 54 58 54 10 e6 b a 57 a a 44 45 56 49 43 45
2e 42 50 42 10 ce 1 1a 16 a 7 8 e4 f 10 7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1 22 16 a 7 8 e4 f 10 7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1 2a 16 a 7 8 e4 f 10
7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1 a 58 a c 53 59 4e 43 49 4e 46 4f 2e 42 50 42 10 5d 1a 16 a 7 8 e4 f 10 7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1 22 16 a
 8 e4 f 10 7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1 2a 16 a 7 8 e4 f 10 7 18 2 12 9 8 a 10 a 18 36 20 bd 7 18 1
        from C:/polar-master/lib/polar_usb_acm.rb:51:in `request'
        from C:/polar-master/lib/polar_ftp.rb:33:in `dir'
        from C:/polar-master/lib/polar_ftp.rb:71:in `recurse'
        from C:/polar-master/lib/polar_ftp.rb:125:in `sync'
        from C:/polar-master/polar_ftp:64:in `<main>'

C:\polar-master>pause

**Comment by tdpo2** [comment]
I guess nobody cares for privacy anymore.

**Comment by cmaion** [comment]
Your attitude is not helping, at all.
This is an open source project developed in spare time for personal use, nobody owes you anything.
Learn how to be a better human being before asking anything, don't make me waste more time.

**Comment by tdpo2** [comment]
Hello! The issue is still not fixed.

Now stuck at 

C:\polar-master>C:\Ruby3021\bin\ruby.exe C:\polar-master\polar_ftp -d//./COM5 SYNC C:\POLARSYNC
Connected to ? serial ?
Synchronizing to 'C:\POLARSYNC'
Listing content of '/'
Downloading '/JOURNAL.DAT' as 'C:\POLARSYNC/JOURNAL.DAT'
