### ISSUE TITLE
Just learn to code, right?

### ISSUE THREAD

**Issue by tdpo2** [cmaion/polar#18]
Attitude would have been better if you wouldn't shut me down.

But I guess you prefer [Polar] corporation and their pedo-stalking goes on.

**Comment by expiredemulsion** [comment]
Well there’s three options. 

1. Accept Polars logging and use their service and analysis. 
2. Don’t accept Polars logging and only use the Vantage itself for limited off grid in watch logging and analysis.
3. Support this project and export the data and log and process itself according to need. 

:)

**Comment by tdpo2** [comment]
How can you do number 3? If it doesn't work.
