### ISSUE TITLE
transfer_timed_out on an RC3 GPS

### ISSUE THREAD

**Issue by git-dino** [cmaion/polar#20]
Hi Cédric, 
Great project!
Found it by chance, giving me hope that I can use my (still fully functional) watch again after being denied access to Polar Flow.
Changed the product id to 6 in polar_usb_hid.rb:7 to get connection with the watch, which works.
Getting the 
Connected to Polar RC3 GPS serial xxx
Listing content of /

but then I get an error transfer_timed_out from submit_transfer in dev_handle.rb
Am not familiar with Ruby but tried some debugging messages, it looks like 64 bytes are read first, giving a status TRANSFER_COMPLETED but then the reading continues and the error occurs.
Any ideas?
Should I be using polar_usb_acm.rb instead, and if so, what should the device option look like?
Running Ruby 2.6 on Win 10, fresh install. Used Process Monitor but saw nothing suspicious.
Any help greatly appreciated.
Grtz, Dino

**Comment by cmaion** [comment]
Hi!

I have absolutely no idea about the USB protocol used by the RC3, and the file format (and what kind of data you can download from the watch).

Even if you can capture a valid USB session (eg, as performed by a Polar software on Windows) & reverse engineer it, I doubt that the file structure is the same as the newer generation watches. I wouldn't get my hopes too high?
