### ISSUE TITLE
couldn't open serial device on /dev/ttyACM0: EACCES

### ISSUE THREAD

**Issue by tdpo2** [cmaion/polar#21]
$ ./polar_ftp
Polar Vantage M serial 12345 found, but couldn't open serial device on /dev/ttyACM0: EACCES
Please specify the device to use with the -d option.
No Polar USB device detected.

edit:

$ sudo ./polar_ftp
Traceback (most recent call last):
	7: from /home/username/polar-master/polar_ftp:4:in `<main>'
	6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	4: from /home/username/polar-master/lib/polar_ftp.rb:3:in `<top (required)>'
	3: from /home/username/polar-master/lib/polar_ftp.rb:3:in `require_relative'
	2: from /home/username/polar-master/lib/polar_usb.rb:1:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- libusb (LoadError)

**Comment by cmaion** [comment]
https://github.com/cmaion/polar/blob/master/README.md#linux
and
https://github.com/cmaion/polar/blob/master/README.md#installation-all-platforms

**Comment by tdpo2** [comment]
I did that.

**Comment by cmaion** [comment]
If you are running `polar_ftp` as root, gems should be installed as root as well (`sudo gem install ...`)

**Comment by tdpo2** [comment]
# ./polar_ftp
Connected to Polar Vantage M serial 12345
Usage:
  /home/user/polar/polar_ftp [options] DIR <directory>
  /home/user/polar/polar_ftp [options] GET <file> [<output_file>]
  /home/user/polar/polar_ftp [options] SYNC [<output_dir>]

Options:
    -d, --dev=DEVICE                 Serial port device (for Polar Ignite, Vantage...)
    -h                               Help


inside polar_ftp: sudo /home/user/polar/polar_ftp polar_ftp DIR /

**Comment by tdpo2** [comment]
PS:

$ sudo cp pkg/99-polar.rules /etc/udev/rules.d
$ sudo udevadm control --reload-rules

Doesn't work.

I have to chmod 666 /dev/ttyACM0 each time I connect the device.

**Comment by be-ndee** [comment]
A little bit late, but I've had the same problem and was always running `sudo chmod 666 /dev/ttyACM0` after connecting the watch. After a little bit of playing around with the udev-rule I figured out the following rule which works for me:

```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0da4", ATTRS{idProduct}=="0014", MODE="0666"
```
