### ISSUE TITLE
activitysamples2csv failed

### ISSUE THREAD

**Issue by henkela** [cmaion/polar#24]
Hi, 
thanks for your scripts to read of polar watches. 

Unfortunately, activitysamples2csv was failing for me with 
Traceback (most recent call last):
	5: from ./polar_activitysamples2csv:91:in `<main>'
	4: from ./polar_activitysamples2csv:91:in `open'
	3: from ./polar_activitysamples2csv:92:in `block in <main>'
	2: from ./polar_activitysamples2csv:71:in `output_csv'
	1: from ./polar_activitysamples2csv:71:in `each'
./polar_activitysamples2csv:75:in `block in output_csv': undefined method `value_to_names_map' for 
PolarData::PbActivityInfo::ActivityClass:Module (NoMethodError)

Since I couldn't find the method value_to_names_map, I had a quick look using pry and found that r[:activity] already contained a String and changing 
activity_name = PolarData::PbActivityInfo::ActivityClass.value_to_names_map[r[:activity]].first.to_s
to 
activity_name = r[:activity].to_s

fixed it for me. I'm using a Vantage M 

Best
Andreas

**Comment by cmaion** [comment]
Hi!

Finally took the time to look into this.
You're right, this was indeed a regression following a previous change to a new protobuf library.
Fixed (as you did) in 4fb92baf6d4a1317bd39594035c0e34d564dd1b0.

Thanks!
