### ISSUE TITLE
polar_ftp error

### ISSUE THREAD

**Issue by awik32** [cmaion/polar#27]
I'm trying to use polar_ftp to sync my Polar Loop 2, and I'm getting the following error:
```
$ ./polar_ftp SYNC
Connected to Polar Loop 2 serial XXXXXXXX
Synchronizing to '/home/aw/Polar/XXXXXXXX'
Listing content of '/'
Traceback (most recent call last):
	8: from ./polar_ftp:64:in `<main>'
	7: from /home/aw/src/polar/lib/polar_ftp.rb:125:in `sync'
	6: from /home/aw/src/polar/lib/polar_ftp.rb:71:in `recurse'
	5: from /home/aw/src/polar/lib/polar_ftp.rb:33:in `dir'
	4: from /home/aw/src/polar/lib/polar_usb_hid.rb:37:in `request'
	3: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `read'
	2: from /home/aw/src/polar/lib/polar_usb_hid.rb:45:in `loop'
	1: from /home/aw/src/polar/lib/polar_usb_hid.rb:68:in `block in read'
/home/aw/src/polar/lib/polar_usb.rb:113:in `process_error': Error: 238? (PolarUsb::PolarUsbError)
```
Regards,
Albert.

**Comment by cmaion** [comment]
No idea what error code 238 is.
IIRC you have been able to sync your Loop 2 a while ago?
Check that your USB connector is clean, unplug/plug, retry...

My V800 sometimes throw various errors, often due to the physical USB connection to the watch. Cleaning it and retrying a couple of times makes it sync again.

**Comment by awik32** [comment]
> IIRC you have been able to sync your Loop 2 a while ago?

Yes.  Today, I was able to sync again without problems.

I'm using Polar FlowSync (PFS) in parallel, running Windows7 in a VMware virtual machine, and if PFS syncs successfully, it would seem the physical connection is all right.

-aw

**Comment by cmaion** [comment]
OK maybe the watch was in an unexpected/specific state left by Polar Flow.
