### ISSUE TITLE
SYNC stalls

### ISSUE THREAD

**Issue by u003f** [cmaion/polar#33]
Whenever I attempt to run `polar_ftp SYNC` (on a Vantage V2) it stalls (left for one hour) at the point `Downloading '/SYS/FONT/ZH_JA.RAW'`. Is there any way to ignore files, or to use `GET` to retrieve multiple files?

**Comment by cmaion** [comment]
Hi,

Does this happen every time you synchronize?

I don't have such files on my own V2 so I can't tell what's wrong.

You may still manually patch lib/polar_ftp.rb, eg, something along the lines of:
```up2date = true if remote_dir =~ /^\/SYS\/FONT\//```
(which would go at line 113, before trying to download the remote file)

**Comment by u003f** [comment]
Yes it hung every time, but your patch fixed it and now it fully syncs. The file is large
`Listing content of '/SYS/FONT/'
   ZH_JA.RAW          5562936`
perhaps that was causing the issue.

**Comment by cmaion** [comment]
All right, could be a bug with large files indeed.
I never encountered files larger than 1MB, so I can't tell for sure.
