### ISSUE TITLE
Timezone when converting to GPX

### ISSUE THREAD

**Issue by jluttine** [cmaion/polar#4]
Thanks for this amazing tool! I just bought V800 and got really annoyed because I thought I can't get the data out in any way (I'm using Linux). Well, this tool made my day!

I noticed the following: When converting a training session to GPX, all timestamps are in UTC (or Zulu) timezone. Could it either use the timezone of my local system (that's most likely correct) or let it be configurable?

**Comment by cmaion** [comment]
Fixed in 1a2547a1928752947b521f397a3084ac4a7555e3?

Pull and let me know -- I don't know if all common GPX importers can read non UTC times.

**Comment by cmaion** [comment]
Closing, I believe that this is fixed.

BTW, you may also try the new TCX converter (still doesn't support multiple sports in a single training session though)
