### ISSUE TITLE
Google protobuf (NoMethodError)

### ISSUE THREAD

**Issue by tdpo2** [cmaion/polar#44]
C:\polar-master>C:\Ruby30\bin\ruby.exe C:\polar-master\polar_ftp SYNC
C:/polar-master/lib/protobuf/types_pb.rb:6:in `<top (required)>': undefined method `build' for #<Google::Protobuf::DescriptorPool:0x06193410> (NoMethodError)
        from <internal:C:/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/polar-master/lib/polar_data_parser.rb:6:in `<top (required)>'
        from C:/polar-master/lib/polar_ftp.rb:4:in `require_relative'
        from C:/polar-master/lib/polar_ftp.rb:4:in `<top (required)>'
        from <internal:C:/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby30/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/polar-master/polar_ftp:4:in `<main>'

Windows 11; Ruby 3.0.2-1-x86-msvcrt with MSYS2

**Comment by cmaion** [comment]
I guess google-protobuf version >= 4 has breaking changes.
Updated Gemfile to limit to versions < 4
